#!/bin/sh

# shell script that extracts and outputs important messages from dmesg logs

# Boot problem
echo "[Messages to see in the log at boot time (dmesg)]"
dmesg | grep -E -i "error|critical|warning|fail|panic|segfault|call trace|oom|fault|not" | grep -viE "default|notice"

echo ""
