#!/bin/sh

echo "Logs for connections:"
echo "[logread]"
logread | grep -i 'connection'
echo ""

# lastlog
echo "[lastlog]"
lastlog
echo ""

# /var/log/secure
echo "[/var/log/secure]"
cat /var/log/secure
