#!/bin/sh

echo "[/etc/shadow check]"

# Check ownership of /etc/shadow file
file="/etc/shadow"
owner=$(stat -c "%U" "$file")

# Check if owner is not root
if [ "$owner" != "root" ]; then
    echo "Warning: /etc/shadow file owner is not root!"
fi

# Check permissions of /etc/shadow file
permission=$(stat -c "%a" "$file")

# Check if permission is not 400 or less
if [ "$permission" -gt 400 ]; then
    echo "Warning: /etc/shadow file permission is not 400 or less!"
fi
