#!/bin/sh

echo "[/etc/hosts check]"

# Check ownership of /etc/hosts file
file="/etc/hosts"
owner=$(stat -c "%U" "$file")

# Check if owner is not root
if [ "$owner" != "root" ]; then
    echo "Warning: /etc/hosts file owner is not root!"
fi

# Check permissions of /etc/hosts file
permission=$(stat -c "%a" "$file")

# Check if permission is not 600 or less
if [ "$permission" -gt 600 ]; then
    echo "Warning: /etc/hosts file permission is not 600 or less!"
fi
