#!/bin/sh

echo "[List for files with SUID or SGID bits set]"

# Script to find and list files with setuid or setgid bits set, owned by root
find / -user root -type f \( -perm -4000 -o -perm -2000 \) -exec ls -lg {} \;
