#!/bin/sh

if [ "$1" = "-t" ]; then
    echo "-------Timeline Analysis-------"
    ./option_t
    echo "DONE"
elif [ "$1" = "-l" ]; then
    echo "---------Log Analysis---------"
    ./option_l
    echo "DONE"
elif [ "$1" = "-f" ]; then
    echo "------Abnormal Files & Directories------"
    ./option_f
    echo "DONE"
elif [ "$1" = "-a" ]; then
    echo "-------Timeline Analysis-------"
    ./option_t
    echo ""
    echo "---------Log Analysis---------"
    ./option_l
    echo ""
    echo "------Abnormal Files & Directories------"
    ./option_f
    echo "DONE"
else
    echo "FT. ELIOT (Forensics Tool for Embedded Linux on IoT devices)"
    echo ""
    echo "Usage: ./ft_eliot [OPTIONS]"
    echo ""
    echo "Perform timeline analysis, log analysis, and abnormal file search on the device"
    echo ""
    echo "        -t      Timeline Analysis"
    echo "        -l      Log Analysis"
    echo "        -f      Abnormal Files & Directories Search"
    echo "        -a      All tasks"
fi
